# Generated by Django 4.1.1 on 2023-05-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0002_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=50)),
                ('date', models.DateTimeField(max_length=100)),
            ],
        ),
    ]
