# Generated by Django 4.1.1 on 2023-05-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0003_commentdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('content', models.TextField(max_length=75)),
                ('date', models.DateTimeField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='CommentData',
        ),
    ]
