# Generated by Django 4.1.1 on 2023-05-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0004_commentinfo_delete_commentdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentinfo',
            name='rating',
            field=models.IntegerField(default=10),
        ),
    ]
