# Generated by Django 4.1.1 on 2023-05-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0007_alter_commentinfo_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentinfo',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
